export type Category = "featured" | "labs" | "community" | "projects" | "legacy";

export interface Project {
  name: string;
  description: string;
  repo: string;
  category: Category;
  language?: string;
  emoji: string;
  isNew?: boolean;
}

export const categoryMeta: Record<Category | "all", { label: string; color: string }> = {
  all: { label: "All", color: "#e4e4ef" },
  featured: { label: "Featured", color: "#06b6d4" },
  labs: { label: "Labs", color: "#8b5cf6" },
  community: { label: "Community", color: "#22c55e" },
  projects: { label: "Projects", color: "#f59e0b" },
  legacy: { label: "Legacy", color: "#71717a" },
};

export const langColors: Record<string, string> = {
  TypeScript: "#3178c6",
  JavaScript: "#f1e05a",
  CSS: "#563d7c",
  HTML: "#e34c26",
  PHP: "#4F5D95",
  Batch: "#C1F12E",
  YAML: "#cb171e",
  Markdown: "#083fa1",
  Python: "#3572A5",
  Go: "#00ADD8",
  Rust: "#dea584",
};

// ── Tiny Claw (Highlight Project) ──
export const tinyClaw = {
  name: "Tiny Claw",
  description: "Ultra-minimal AI companion that learns",
  repo: "warengonzaga/tinyclaw",
  language: "TypeScript",
  emoji: "🤖🧠🐜",
};

export const projects: Project[] = [
  // ── Featured (Current Projects) ──
  {
    name: "Magic Commit",
    description: "AI-powered Git commit message generator",
    repo: "warengonzaga/magic-commit",
    category: "featured",
    language: "TypeScript",
    emoji: "🪄📝🤖",
  },
  {
    name: "Magic Release",
    description: "AI-powered release notes generator",
    repo: "warengonzaga/magic-release",
    category: "featured",
    language: "TypeScript",
    emoji: "🪄🚀🤖",
  },

  // ── Labs (WG Tech Labs) ──
  {
    name: "GitHub Copilot Chat Modes",
    description: "AI agents for smarter open-source projects",
    repo: "wgtechlabs/github-copilot-chatmodes",
    category: "labs",
    language: "Markdown",
    emoji: "🤖💬🧩",
  },
  {
    name: "Clean Commit",
    description: "Clean code deserves clean commits",
    repo: "wgtechlabs/clean-commit",
    category: "labs",
    language: "TypeScript",
    emoji: "🧹📝✅",
  },
  {
    name: "Forum Support Discord Bot",
    description: "Forum-based support bot for Discord",
    repo: "wgtechlabs/forum-support-discord-bot",
    category: "labs",
    language: "TypeScript",
    emoji: "💬🤝🎮",
  },
  {
    name: "Unthread Discord Bot",
    description: "Unthread ticketing system for Discord",
    repo: "wgtechlabs/unthread-discord-bot",
    category: "labs",
    language: "TypeScript",
    emoji: "🎫🤖🎮",
  },
  {
    name: "Log Engine",
    description: "Node.js logging solution",
    repo: "wgtechlabs/log-engine",
    category: "labs",
    language: "TypeScript",
    emoji: "📋🔍🛠️",
  },
  {
    name: "Secrets Engine",
    description: "Secure secret storage SDK for TypeScript",
    repo: "wgtechlabs/secrets-engine",
    category: "labs",
    language: "TypeScript",
    emoji: "🔐🗝️🛡️",
  },
  {
    name: "Config Engine",
    description: "Fast, Bun-first configuration SDK",
    repo: "wgtechlabs/config-engine",
    category: "labs",
    language: "TypeScript",
    emoji: "⚙️📦🔧",
  },
  {
    name: "Unthread Telegram Bot",
    description: "Telegram to Unthread support tickets",
    repo: "wgtechlabs/unthread-telegram-bot",
    category: "labs",
    language: "TypeScript",
    emoji: "🎫🤖✈️",
  },
  {
    name: "Unthread WhatsApp Bot",
    description: "WhatsApp to Unthread support tickets",
    repo: "wgtechlabs/unthread-whatsapp-bot",
    category: "labs",
    language: "TypeScript",
    emoji: "🎫🤖💬",
  },
  {
    name: "Container Build Flow",
    description: "Docker container build automation action",
    repo: "wgtechlabs/container-build-flow-action",
    category: "labs",
    language: "YAML",
    emoji: "🐳🔄📦",
  },
  {
    name: "Package Build Flow",
    description: "NPM package build automation action",
    repo: "wgtechlabs/package-build-flow-action",
    category: "labs",
    language: "YAML",
    emoji: "📦🔄🚀",
  },
  {
    name: "Release Build Flow",
    description: "Automated release creation action",
    repo: "wgtechlabs/release-build-flow-action",
    category: "labs",
    language: "YAML",
    emoji: "🏷️🔄🚀",
  },
  {
    name: "Unthread Webhook Server",
    description: "Unthread webhook server",
    repo: "wgtechlabs/unthread-webhook-server",
    category: "labs",
    language: "TypeScript",
    emoji: "🪝🖥️🔗",
  },
  {
    name: "Nuvex",
    description: "Structured memory SDK for AI agents",
    repo: "wgtechlabs/nuvex",
    category: "labs",
    language: "TypeScript",
    emoji: "🧠💾🤖",
  },
  {
    name: "Unthread Webhook SDK",
    description: "Unthread webhook TypeScript SDK",
    repo: "wgtechlabs/unthread-webhook-sdk",
    category: "labs",
    language: "TypeScript",
    emoji: "🪝📦🔗",
  },
  {
    name: "Is Railway",
    description: "Detect if running on Railway platform",
    repo: "wgtechlabs/is-railway",
    category: "labs",
    language: "TypeScript",
    emoji: "🚂🔍☁️",
  },
  {
    name: "OSV Framework",
    description: "Open Sponsor Value Framework",
    repo: "wgtechlabs/osv-framework",
    category: "labs",
    language: "Markdown",
    emoji: "💰📐🤝",
  },
  {
    name: "Zentrynel",
    description: "Discord moderation bot",
    repo: "wgtechlabs/zentrynel",
    category: "labs",
    language: "TypeScript",
    emoji: "🛡️🤖🎮",
  },

  // ── Projects (Open Source) ──
  {
    name: "CSS Text Portrait Builder",
    description: "Create stunning portraits using pure CSS",
    repo: "warengonzaga/css-text-portrait-builder",
    category: "projects",
    language: "CSS",
    emoji: "🎨🖼️✨",
  },
  {
    name: "GitHub Repo Banner",
    description: "Customizable GitHub repository banners",
    repo: "warengonzaga/github-repo-banner",
    category: "projects",
    language: "HTML",
    emoji: "🏷️🖼️🐙",
    isNew: true,
  },
  {
    name: "WiFi Passview",
    description: "WiFi password viewer for Windows",
    repo: "warengonzaga/wifi-passview",
    category: "projects",
    language: "Batch",
    emoji: "📶🔑👀",
  },
  {
    name: "WRN Cleaner",
    description: "Windows maintenance and cleanup tool",
    repo: "warengonzaga/wrn-cleaner",
    category: "projects",
    language: "Batch",
    emoji: "🧹💻🗑️",
  },
  {
    name: "Buy Me a Coffee.js",
    description: "Buy Me a Coffee JavaScript SDK",
    repo: "warengonzaga/buymeacoffee.js",
    category: "projects",
    language: "JavaScript",
    emoji: "☕💛📦",
  },
  {
    name: "Fork Corner",
    description: "GitHub/GitLab fork corner label for your site",
    repo: "warengonzaga/fork-corner",
    category: "projects",
    language: "JavaScript",
    emoji: "🍴📌🌐",
  },
  {
    name: "Love Cards",
    description: "Interactive love cards web app",
    repo: "warengonzaga/love-cards",
    category: "projects",
    language: "HTML",
    emoji: "💌❤️✨",
  },
  {
    name: "IPFS Support Extension",
    description: "IPFS browser support extension",
    repo: "warengonzaga/ipfs-support-extension",
    category: "projects",
    language: "JavaScript",
    emoji: "🌐📦🔌",
  },
  {
    name: "Arweave Support Extension",
    description: "Arweave browser support extension",
    repo: "warengonzaga/arweave-support-extension",
    category: "projects",
    language: "JavaScript",
    emoji: "🌐💎🔌",
  },
  {
    name: "Is It Relay",
    description: "Relay Protocol detector utility",
    repo: "warengonzaga/is-it-relay",
    category: "projects",
    language: "TypeScript",
    emoji: "🔍🔗⚡",
  },
  {
    name: "Relay Protocol Indexer App",
    description: "Relay Protocol data indexer application",
    repo: "warengonzaga/relay-protocol-indexer-app",
    category: "projects",
    language: "TypeScript",
    emoji: "📊🔗🗄️",
  },
  {
    name: "Relay Protocol Stats",
    description: "Relay Protocol analytics dashboard",
    repo: "warengonzaga/relay-protocol-stats",
    category: "projects",
    language: "TypeScript",
    emoji: "📈🔗📊",
  },
  {
    name: "PCSO 2D Lotto Generator",
    description: "PCSO 2D lotto number generator",
    repo: "warengonzaga/pcso-2d-lotto-generator",
    category: "projects",
    language: "JavaScript",
    emoji: "🎲🔢🍀",
  },
  {
    name: "ExpandURL CLI",
    description: "CLI tool to expand shortened URLs",
    repo: "warengonzaga/expandurl-cli",
    category: "projects",
    language: "TypeScript",
    emoji: "🔗🔍💻",
  },
  {
    name: "GitHub Labels Template",
    description: "Apply curated GitHub labels to your repo",
    repo: "warengonzaga/github-labels-template",
    category: "projects",
    language: "JavaScript",
    emoji: "🏷️🎨🐙",
    isNew: true,
  },
  {
    name: "Gumroad TS",
    description: "Gumroad TypeScript SDK",
    repo: "warengonzaga/gumroad-ts",
    category: "projects",
    language: "TypeScript",
    emoji: "🛒💰📦",
  },
  {
    name: "Contribute Now",
    description: "Git workflow automation CLI tool",
    repo: "warengonzaga/contribute-now",
    category: "projects",
    language: "JavaScript",
    emoji: "🤝🔄💻",
    isNew: true,
  },

  // ── Legacy ──
  {
    name: "Animate.css",
    description: "Cross-browser library of CSS animations",
    repo: "animate-css/animate.css",
    category: "legacy",
    language: "CSS",
    emoji: "✨🎭🎬",
  },
  {
    name: "COVID-19 Tracker CLI",
    description: "COVID-19 statistics tracker for the terminal",
    repo: "OSSPhilippines/covid19-tracker-cli",
    category: "legacy",
    language: "JavaScript",
    emoji: "🦠📊💻",
  },
  {
    name: "Matuto",
    description: "Web3 educational browser extension",
    repo: "Web3Philippines/matuto",
    category: "legacy",
    language: "TypeScript",
    emoji: "📚🌐🧩",
  },
  {
    name: "Gather Town.js",
    description: "Gather Town JavaScript SDK",
    repo: "warengonzaga/gathertown.js",
    category: "legacy",
    language: "JavaScript",
    emoji: "🏘️👥📦",
  },
  {
    name: "Daisy.js",
    description: "Web animation plugin for particle systems",
    repo: "warengonzaga/daisy.js",
    category: "legacy",
    language: "JavaScript",
    emoji: "🌸✨🎆",
  },
  {
    name: "thirdweb WP",
    description: "thirdweb WordPress plugin",
    repo: "warengonzaga/thirdweb-wp",
    category: "legacy",
    language: "PHP",
    emoji: "🌐🔌📰",
  },
];
